apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shopping-cart-web
    spec:
      containers:
        - name: shopping-cart-web
          image: stwomack/shopping-cart-web:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-secrets