apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-web-service
spec:
  selector:
    app: shopping-cart-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer